### ISSUE TITLE
Asig.window_op()

### ISSUE THREAD

**Issue by thomas-hermann** [interactive-sonification/pya#11]
window_op() doesn't work with multi-channel signals.
Problem is in scipy.signal.get_window, which throws an "ValueError: operands could not be broadcast together with shapes (1024,2) (1024,) "

**Comment by wiccy46** [comment]
I added some fix to the window_op and window() to make it work for multichannel. Also added the test. The solution here may not be elegant. Please take a look and maybe you might have a better solution.

**Comment by aleneum** [comment]
you know you can reference issues in commit messages. `commit -a -m "deals with window_op (see #11)"`. This way commits will be assigned to the related issue. You can even close issues with `commit -a -m "this closes #11"` (see [here](https://help.github.com/en/articles/closing-issues-using-keywords)).

**Comment by wiccy46** [comment]
Noted.

**Comment by aleneum** [comment]
I added some comment to 2c921a5
