### ISSUE TITLE
Streamlining data access in Arecorder

### ISSUE THREAD

**Issue by aleneum** [interactive-sonification/pya#14]
Arecorder introduces multiple rather simple methods:

```python
    def reset_recordings(self):
        self.recordings = []

    def get_latest_recording(self):
        return self.recordings[-1]
```

I wonder if these methods considerably improve the user experience to justify their maintenance. If they make it into a release they cannot (or should not) be removed without a deprecation phase. I'd suggest to advocate direct manipulation of `self.recording` instead:

```python
ar.reset_recordings() => ar.recordings.clear()
ar.get_latest_recording() => ar.recordings[-1]
while ar.recordings:
    process(ar.recordings.pop())  # FILO
    process(ar.recordings.pop(0))  # FIFO
```

**Comment by thomas-hermann** [comment]
I agree with you. More pythonic to interact with recordings directly. 
I didn't know the clear() method before. nice :-)
It;s also better if users have less method names to remember. 
I have removed the two methods in
