### ISSUE TITLE
Bug: Arecorder is using the wrong channels attribute to wrap channels into columns

### ISSUE THREAD

**Issue by wiccy46** [interactive-sonification/pya#21]
Currently, there is a bug in the Arecorder callback:

data_float = np.reshape(sigar, (len(sigar) // self.channels, self.channels))

while it should be 

data_float = np.reshape(sigar, (len(sigar) // self.input_channels, self.input_channels))

In the 0.3.0 Arecorder I introduced input_channels and input_devices originally to separate from Aserver's channels and device. But since Arecorder will have no output and Aserver has no input. This separation is not that necessary anymore as it will not create confusion. 

I made a fix that now Arecorder also uses device and channels as attributes. 

Patching 0.3.0 to 0.3.1 is required asap as with the current bug, users will get the wrong recordings if their audio device has > 2 input channels. 

This can also be a release for the new backend.

**Comment by aleneum** [comment]
@wiccy46: If you are done with patching and preparing a release (update Changelog; check versioning and Readme.md, ...) create a new issue for releasing and assign it to me. I will release asap then.

**Comment by wiccy46** [comment]
@aleneum , do you think I should just make a hot fix branch from master then make the fix. And leave the develop for future release as it has the backend. If so I will make a hot fix branch and move all the issue related changes there.
