### ISSUE TITLE
Release 0.3.1

### ISSUE THREAD

**Issue by wiccy46** [interactive-sonification/pya#22]
- [x] update version
- [x] review Changelog
- [x] update build tools: `pip3 install -U setuptools twine wheel`
- [x] run tox: `tox`
- [x] clear dist: `rm -r build/ dist/ pya.egg-info/`
- [x] build release: `python3 setup.py sdist bdist_wheel`
- [x] test publication: `twine upload --repository-url https://test.pypi.org/legacy/ dist/*`
- [x] review test publication: https://test.pypi.org/project/pya
- [x] install test release: `pip3 install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple pya`
- [x] publication: `twine upload dist/*`
- [x] install release: `pip3 install pya`
- [x] commit and draft release: https://github.com/interactive-sonification/pya/releases

**Comment by aleneum** [comment]
Released
