### ISSUE TITLE
Improve Asig indexing

### ISSUE THREAD

**Issue by dreinsch** [interactive-sonification/pya#34]
I found the following problems with the current implementation of Asig channel indexing
1. Currently Asig indexing does ignore anything that is not instance of list, int, slice, str into the channel index and it will assume `slice(None, None, None)` because of  Asig.py line 260 https://github.com/interactive-sonification/pya/blob/cb192082e9d6bee90f86a5f0b14d654a526ce477/pya/Asig.py#L260-L262
   
   - Example of using something that will be ignored 

     Code Example:
   ```python
    a = pya.Asig(np.arange(10, 0, -1).reshape(2, 5), 2)
    a.sig
    # array([[10.,  9.,  8.,  7.,  6.],
    #        [ 5.,  4.,  3.,  2.,  1.]], dtype=float32)

    a[:, bytes('This makes no sense', 'utf-8')].sig  # Channel selection with something
    # array([[10.,  9.,  8.,  7.,  6.],
    #        [ 5.,  4.,  3.,  2.,  1.]], dtype=float32)

    ```

   - However it would be useful to allow types like `numpy.ndarray`

     Code Example:
     ```python
      a = pya.Asig(np.arange(10, 0, -1).reshape(2, 5), 2)
      a.sig
      # array([[10.,  9.,  8.,  7.,  6.],
      #        [ 5.,  4.,  3.,  2.,  1.]], dtype=float32)

      order = np.argsort(a.rms())
      # array([4, 3, 2, 1, 0], dtype=int64)

      a[:, order].sig
      # array([[10.,  9.,  8.,  7.,  6.],
      #        [ 5.,  4.,  3.,  2.,  1.]], dtype=float32)
      # instead of correctly reversed

      order = np.array([4, 3, 2, 1, 0])
      a.sig[:, order]
      # array([[ 6.,  7.,  8.,  9., 10.],
      #        [ 1.,  2.,  3.,  4.,  5.]], dtype=float32)

      ```

   
3. When using lists with numpy data types like `numpy.int32` indexing fails. The current implementation only checks for str, bool and int. cidx will remain unset resulting in `UnboundLocalError: local variable 'cidx' referenced before assignment` at Asig.py line 264
https://github.com/interactive-sonification/pya/blob/cb192082e9d6bee90f86a5f0b14d654a526ce477/pya/Asig.py#L263-L264

    Code Example:
    ```python
    a = pya.Asig(np.arange(10, 0, -1).reshape(2, 5), 2)
    a.sig
    # array([[10.,  9.,  8.,  7.,  6.],
    #        [ 5.,  4.,  3.,  2.,  1.]], dtype=float32)

    order_list = list(np.array([4, 3, 2, 1, 0]))
    a[:, order_list].sig
    # UnboundLocalError: local variable 'cidx' referenced before assignment at Asig.py line 264
    ```

Row indexing works because of Asig.py line 227 https://github.com/interactive-sonification/pya/blob/cb192082e9d6bee90f86a5f0b14d654a526ce477/pya/Asig.py#L227-L229

**Comment by aleneum** [comment]
Hi @dreinsch, I just released `pya` 0.3.3 with some fixes considering this. Thank you for filing this issue 👍 !
