### ISSUE TITLE
Python 3.10 support 

### ISSUE THREAD

**Issue by wiccy46** [interactive-sonification/pya#58]
Python 3.10 requires a bump in PyAudio.

**Comment by aleneum** [comment]
FYI: https://community.anaconda.cloud/t/update-conda-package-pyaudio-to-version-0-2-12/47148

**Comment by wiccy46** [comment]
Keep open for now. `pya 0.5.1` supports Python310. But installation on Python310 can not be directly installed via conda yet (except Linux).
