### ISSUE TITLE
Publish 0.3.0

### ISSUE THREAD

**Issue by aleneum** [interactive-sonification/pya#7]
Will release when #6 has been resolved.

## Release Checklist

- [x] update version
- [x] review Changelog
- [x] update build tools: `pip3 install -U setuptools twine wheel`
- [x] run tox: `tox`
- [x] clear dist: `rm -r build/ dist/ pya.egg-info/`
- [x] build release: `python3 setup.py sdist bdist_wheel`
- [x] test publication: `twine upload --repository-url https://test.pypi.org/legacy/ dist/*`
- [x] review test publication: https://test.pypi.org/project/pya
- [x] install test release: `pip3 install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple pya`
- [x] publication: `twine upload dist/*`
- [x] install release: `pip install pya`
- [x] commit and draft release: https://github.com/interactive-sonification/pya/releases

**Comment by aleneum** [comment]
@thomas-hermann, @wiccy46: Should I start the release workflow now or is there more you want to do first. Right now there is no other Issue open related to 0.3.0.

**Comment by wiccy46** [comment]
I would say yes. We can keep any future update to future patches or minor  @thomas-hermann ?

**Comment by thomas-hermann** [comment]
yes, thanks. No pressing issues right now. All other improvements can go into future minor.
